use anchor_lang::InstructionData;
use anchor_lang::prelude::*;
use solana_sdk::instruction::{AccountMeta, Instruction};
use crate::solana::{get_env_pubkey, VAULT_SEED, USER_POSITION_SEED};

pub fn build_borrow_ix(
    user: Pubkey,
    amount_lamports: u64,
) -> Instruction {
    let program_id = get_env_pubkey("PROGRAM_ID");
    
    // 1. Derive PDAs
    let (vault_pda, _) = Pubkey::find_program_address(&[VAULT_SEED], &program_id);
    let (user_position_pda, _) = Pubkey::find_program_address(
        &[USER_POSITION_SEED, user.as_ref()], 
        &program_id
    );

    // 2. Account Meta List (Must match borrow.rs struct order)
    let accounts = vec![
        AccountMeta::new(user, true),                               // Signer
        AccountMeta::new(vault_pda, false),                         // Mut
        AccountMeta::new(user_position_pda, false),                // Mut
        AccountMeta::new_readonly(get_env_pubkey("SOL_PRICE"), false), // Pyth SOL
        AccountMeta::new_readonly(get_env_pubkey("EUR_PRICE"), false), // Pyth EUR
        AccountMeta::new_readonly(solana_program::sysvar::clock::ID, false),
    ];

    // 3. Anchor Instruction Serialization
    // Note: lending_vault::instruction::Borrow is generated by Anchor
    let ix_data = lending_vault::instruction::Borrow { amount: amount_lamports };

    Instruction {
        program_id,
        accounts,
        data: ix_data.data(), // This includes the 8-byte discriminator
    }
}